### ISSUE TITLE
Pull requests merged here

### ISSUE THREAD

**Issue by maxime1907** [srcdslab/sourcebans-pp#1]
List of pull requests:

- https://github.com/sbpp/sourcebans-pp/pull/752
- https://github.com/sbpp/sourcebans-pp/pull/711
- https://github.com/sbpp/sourcebans-pp/pull/764
- https://github.com/sbpp/sourcebans-pp/pull/787
- https://github.com/sbpp/sourcebans-pp/pull/781
- https://github.com/sbpp/sourcebans-pp/pull/786
- https://github.com/sbpp/sourcebans-pp/pull/769
- https://github.com/sbpp/sourcebans-pp/pull/763
- https://github.com/sbpp/sourcebans-pp/pull/718

**Comment by Rushaway** [comment]
Can be closed. Outdated. Related to PHP 7.4
