### ISSUE TITLE
Php 7.4 end of support

### ISSUE THREAD

**Issue by maxime1907** [srcdslab/sourcebans-pp#4]
Php 7.4 end of line support is planned 28 November 2022.

Sourcebans pp need to be updated to support PHP 8.

To-do list will be added later.

**Comment by Rushaway** [comment]
PHP 8.1 support start be added : Wait for stable release.
Follow : https://github.com/sbpp/sourcebans-pp/tree/php81

**Comment by maxime1907** [comment]
Nice yes we will do this :slightly_smiling_face:

**Comment by maxime1907** [comment]
php81 is now our default branch
