### ISSUE TITLE
[SourceBans++] This player has not been verified. Please wait thirty seconds before retrying.

### ISSUE THREAD

**Issue by SyntX34** [srcdslab/sourcebans-pp#9]
i didnt found any error log in my server for sourcebans however bans are working fine but while muting/gaging players this error occurs. Any idea how to fix this?

OS : ubuntu22.04
MySql Version: 8.0.32-0ubuntu0.22.04.2 for Linux on x86_64 ((Ubuntu))
Php Version: 8.1
Sourcebans Version:  1.7.0
Sourcebans (Ingame): 1.8.0 - updated

**Comment by Rushaway** [comment]
Fixed in 1db89f9
